#!/usr/bin/env python3
"""
plot_re_dr_scatter.py  —  Generate RE/DR scatter plots across all 8 methods.

Run this AFTER all re_dr_analysis.py SLURM array tasks have finished.
It collects each method's re_dr_summary.csv, concatenates them, and produces:
  scatter_weightDR_{y_expr}_vs_{x_expr}_{re_metric}_{tag}.png
  scatter_scoreDR_{y_expr}_vs_{x_expr}_{re_metric}_{tag}.png

These are the 2 plots originally generated by re_dr_dual_path_robust_cv.py
in the Handover package, which could not be produced per-method (need all 8).

Usage:
  python method_selection/plot_re_dr_scatter.py
  python method_selection/plot_re_dr_scatter.py --out_dir plots
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


DEFAULT_RE_DR_ROOT = "method_selection_out/re_dr"
DEFAULT_OUT_DIR    = "plots"

METHOD_COLORS = {
    "GradDiff": "#e41a1c",
    "RMU":      "#377eb8",
    "RMU-LAT":  "#4daf4a",
    "RepNoise": "#984ea3",
    "ELM":      "#ff7f00",
    "RR":       "#a65628",
    "TAR":      "#f781bf",
    "PB_J":     "#999999",
}


def load_all_summaries(re_dr_root: str, train_scheme: str, train_window_id: str) -> pd.DataFrame:
    tag = f"{train_scheme}_{train_window_id}"
    root = Path(re_dr_root)
    frames = []
    for method_dir in sorted(root.iterdir()):
        csv_path = method_dir / tag / "re_dr_summary.csv"
        if csv_path.exists():
            df = pd.read_csv(csv_path)
            frames.append(df)
        else:
            print(f"WARNING: {csv_path} not found — skipping {method_dir.name}")
    if not frames:
        raise FileNotFoundError(
            f"No re_dr_summary.csv files found under {re_dr_root}. "
            "Run re_dr_analysis.py first."
        )
    combined = pd.concat(frames, ignore_index=True)
    print(f"Loaded {len(frames)} method summaries: {sorted(combined['method'].tolist())}")
    return combined


def make_scatter(df: pd.DataFrame, x_col: str, y_col: str, out_path: str, title: str) -> None:
    fig, ax = plt.subplots(figsize=(8, 6))
    for _, row in df.iterrows():
        method = str(row["method"])
        color = METHOD_COLORS.get(method, "#333333")
        ax.scatter(row[x_col], row[y_col], s=120, color=color, zorder=5)
        ax.annotate(
            f"  {method}",
            (row[x_col], row[y_col]),
            fontsize=9, va="center", color=color,
        )
    ax.axhline(0, linewidth=1, linestyle="--", color="gray")
    ax.axvline(0, linewidth=1, linestyle="--", color="gray")
    ax.set_xlabel(x_col, fontsize=11)
    ax.set_ylabel(y_col, fontsize=11)
    ax.set_title(title, fontsize=12)
    ax.grid(True, alpha=0.2)
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()
    print(f"Saved: {out_path}")


def main():
    ap = argparse.ArgumentParser(
        description="Generate RE/DR scatter plots across all 8 unlearning methods."
    )
    ap.add_argument("--re_dr_root",      default=DEFAULT_RE_DR_ROOT)
    ap.add_argument("--train_scheme",    default="full", choices=["full", "traincv"])
    ap.add_argument("--train_window_id", default="full")
    ap.add_argument("--subset_mode",     default="none")
    ap.add_argument("--eval_split",      default="test")
    ap.add_argument("--x_expr",          default="DR_late_minus_mid",
                    help="Column to use as x-axis (must exist in re_dr_summary.csv)")
    ap.add_argument("--y_expr",          default="RE_mid_minus_early",
                    help="Column to use as y-axis (must exist in re_dr_summary.csv)")
    ap.add_argument("--re_metric",       default="auc", choices=["auc", "acc"])
    ap.add_argument("--out_dir",         default=DEFAULT_OUT_DIR)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    df = load_all_summaries(args.re_dr_root, args.train_scheme, args.train_window_id)

    # Build axis values from the summary columns
    # x_weight / x_score / y_re are pre-computed by re_dr_analysis.py
    # but we may also want to support named band expressions directly.
    tag = f"{args.train_scheme}_{args.train_window_id}_{args.subset_mode}_{args.eval_split}"

    # Map user expressions to available columns
    x_weight_col = "x_weight"
    x_score_col  = "x_score"
    y_re_col     = "y_re"

    missing = [c for c in [x_weight_col, x_score_col, y_re_col] if c not in df.columns]
    if missing:
        raise ValueError(
            f"re_dr_summary.csv is missing columns: {missing}. "
            "These are built by re_dr_analysis.py with --x_expr / --y_expr. "
            f"Available columns: {list(df.columns)}"
        )

    weight_png = os.path.join(
        args.out_dir,
        f"scatter_weightDR_{args.y_expr}_vs_{args.x_expr}_{args.re_metric}_{tag}.png",
    )
    score_png = os.path.join(
        args.out_dir,
        f"scatter_scoreDR_{args.y_expr}_vs_{args.x_expr}_{args.re_metric}_{tag}.png",
    )
    # Simplified PDF names for paper inclusion
    weight_pdf = os.path.join(args.out_dir, "re_dr_scatter_weight.pdf")
    score_pdf  = os.path.join(args.out_dir, "re_dr_scatter_score.pdf")

    weight_title = (
        f"Weight-space DR: {args.y_expr} vs {args.x_expr}\n"
        f"({args.re_metric.upper()}, {tag}, n={len(df)} methods)"
    )
    score_title = (
        f"Score-space DR: {args.y_expr} vs {args.x_expr}\n"
        f"({args.re_metric.upper()}, {tag}, n={len(df)} methods)"
    )

    make_scatter(
        df.rename(columns={x_weight_col: args.x_expr, y_re_col: args.y_expr}),
        x_col=args.x_expr, y_col=args.y_expr,
        out_path=weight_png, title=weight_title,
    )
    make_scatter(
        df.rename(columns={x_weight_col: args.x_expr, y_re_col: args.y_expr}),
        x_col=args.x_expr, y_col=args.y_expr,
        out_path=weight_pdf, title=weight_title,
    )

    make_scatter(
        df.rename(columns={x_score_col: args.x_expr, y_re_col: args.y_expr}),
        x_col=args.x_expr, y_col=args.y_expr,
        out_path=score_png, title=score_title,
    )
    make_scatter(
        df.rename(columns={x_score_col: args.x_expr, y_re_col: args.y_expr}),
        x_col=args.x_expr, y_col=args.y_expr,
        out_path=score_pdf, title=score_title,
    )

    print(f"\nDone. Scatter plots saved to {args.out_dir}/")


if __name__ == "__main__":
    main()
